### ISSUE TITLE
overlayVariableDetails malformed in some back end responses for low-cardinality numeric variables

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/plot.data#134] opened 2022-02-27 17:00 UTC
Related to VEuPathDB/web-eda#914 

Not for b56 at this late hour!

Here is a GEMS1 barplot for country, overlay = categorical wealth

![image](https://user-images.githubusercontent.com/308639/155891831-645aff3d-b709-4ed3-beda-9895c2e7653d.png)

Looks like the overlayVariableDetails object is missing in the response:

```
{
	"0": {
		"PCO_0000024.EUPATH_0000143": 2,
		"label": [
			"Bangladesh",
			"India",
			"Kenya",
			"Mali",
			"Mozambique",
			"Pakistan",
			"The Gambia"
		],
		"value": [
			759,
			795,
			826,
			820,
			385,
			722,
			520
		]
	}
}
```

**Comment by bobular** [comment] 2022-02-28 16:41
Was linked to the wrong issue and shouldn't have been closed, sorry!

**Comment by bobular** [comment] 2022-02-28 16:42
It should probably go to @d-callan first, Steph

**Comment by d-callan** [comment] 2022-04-12 16:21
@bobular i cant reproduce. did you filter, use a specific gems or something?

**Comment by bobular** [comment] 2022-04-12 16:49
I can't reproduce it either.  I doubt I used other than regular GEMS1 

![image](https://user-images.githubusercontent.com/308639/163013578-906732d4-2d0f-487c-8fb7-22f29249e2db.png)

**Comment by d-callan** [comment] 2022-04-12 17:05
ill close it then. can always reopen if it resurfaces.

**Comment by bobular** [comment] 2022-04-12 17:51
I'm sorry - there was a subset which I didn't document and can't reproduce now.  My bad!

**Comment by SheenaTomko** [comment] 2022-04-13 19:30
Jay reloaded the data (see https://github.com/VEuPathDB/EdaLoadingIssues/issues/27), and now the legend shows up, but the plot is empty once you add the overlay value. 
<img width="1118" alt="Screen Shot 2022-04-13 at 2 28 47 PM" src="https://user-images.githubusercontent.com/54597319/163255780-ca46dc10-7ee6-4e83-917d-e6684937e9c9.png">

**Comment by d-callan** [comment] 2022-04-14 15:22
oof ill bet the backend is seeing a continuous variable and assuming were going to do a continuous overlay. @asizemore any chance you have a second to look at this?

**Comment by asizemore** [comment] 2022-04-14 15:38
@d-callan i'll look into it!

**Comment by asizemore** [comment] 2022-04-14 15:41
Looks like this issue has only been seen in bar plots so far?

**Comment by d-callan** [comment] 2022-04-14 15:44
only reported there, but id rather not make that assumption

**Comment by asizemore** [comment] 2022-04-14 15:47
are these numeric categoricals getting a data shape of "continuous"?

**Comment by d-callan** [comment] 2022-04-14 15:57
Numbers are always continuous now regardless of cardinality. If they actually represent labels then the clinepi team annotate them w 'forceStringType' and they will be loaded as categorical strings instead.

**Comment by asizemore** [comment] 2022-04-14 16:19
Not restricted to bar. Had a hunch scatter should be messing up as well and indeed it is

![Screen Shot 2022-04-14 at 12 18 45 PM](https://user-images.githubusercontent.com/11710234/163431431-2ef86b81-1a23-4000-99eb-990a866ba597.png)

**Closed** 2022-04-15 16:24 UTC
Labels: bug, high priority, b57

**Comment by SheenaTomko** [comment] 2022-04-18 13:42
Qa'd on GEMS and PRISM and this looks good
