### ISSUE TITLE
Visualizations: default binWidth from back end is outside the histogram response's own min/max range.

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/plot.data#99] opened 2021-10-04 12:54 UTC
Study: India ICEMR Fever Surveillance
Viz: histogram
Var: Chikungunya OD value, by SD Bioline IgM ELISA result

request POST
```
{"config":
{"barMode":"stack",
"binSpec":{"type":"binWidth"},
"outputEntityId":"EUPATH_0000609","showMissingness":"FALSE","valueSpec":"count",
"xAxisVariable":{"entityId":"EUPATH_0000609","variableId":"EUPATH_0021108"}}}
```

response (fragment)
```
{"binSlider":{"min":0.1,"max":0.69,"step":0.1}}
{"binSpec":{"type":"binWidth","value":0.09}}
```

As you can see, 0.09 is less than the min.  This is causing a red border on the bin width UI element in the client, but no other adverse effects, so this is minor - could be slipped to Phase 2

**Comment by danicahelb** [comment] 2021-10-05 03:51
I'm adding a picture because it took me a while to see what the issue was:
![image](https://user-images.githubusercontent.com/25450900/135957296-d23baf76-836e-4a0f-8fc3-43d302a961bd.png)

I don't understand why this is happening?

**Comment by d-callan** [comment] 2021-10-05 17:53
i see it. its not a precision difference between .09 and .1 after all. apparently if plot.data tries to find bin slider min, step values and gets a 0 back it defaults to 0.1. ive changed the way it finds these values so its much less likely to ever get a 0, and therefore default to something that may or may not make sense. ill do a bit more testing and then close this.

**Comment by d-callan** [comment] 2021-10-05 18:10
rserve v1.3.11 plot.data v1.2.7

**Comment by danicahelb** [comment] 2021-10-08 19:33
I still don't understand what the issue is... but I found another instance where the bin width box is outlined in red

See wash-b kenya, "Age at symptoms"

![image](https://user-images.githubusercontent.com/25450900/136615466-a820a1f4-727f-43eb-84ce-a7f601ace506.png)

**Closed** 2021-10-08 21:39 UTC
Labels: bug
