### ISSUE TITLE
Bug: lineplot proportion throws client-side error

### ISSUE THREAD

**Issue by jernestmyers** [VEuPathDB/plot.data#194] opened 2022-08-23 21:52 UTC
To create the bug:
1. Create a new Line Plot viz in any study (`Amazonia ICEMR Brazil Cohort` is my go-to)
2. Select an x-variable related to Dates, like `Participant: Observation Date` in Amazonia Brazil
3. Select any categorical y-variable, like `Sex` in Amazonia Brazil
4. Set the numerator for the proportion
5. Client side error will result as shown in the screenshot below

In the screenshot, I've included a glimpse of the API response from the data service.

![image](https://user-images.githubusercontent.com/69446567/186273029-1612d28f-e6fa-4f56-b4cf-d073e0346b91.png)

**Comment by asizemore** [comment] 2022-08-24 17:45
@moontrip do you remember which other data the date did not have the time zone part? I just looked at a random variable in Histogram and i'm seeing the response also includes the time zone there as well.

<img width="1688" alt="Screen Shot 2022-08-24 at 1 45 03 PM" src="https://user-images.githubusercontent.com/11710234/186487598-b1fcbecd-2c20-4d59-973c-8076c7aaa688.png">

**Comment by moontrip** [comment] 2022-08-24 18:16
Hi @asizemore Interesting! I play with Scatterplot in many cases (😄) and I checked GEMS1 Case Control with Scatter plot. Also checked some date variable like Observation date (@jernestmyers Jeremy reported) and Birth date (you used above) and they both returned yyyy-mm-dd format without 'T'. So it looks like backend response is inconsistent per Viz response. 

Actually there is a code/function to deal with such a case, https://github.com/VEuPathDB/web-eda/blob/9ce4cafdd8883347495a04b905137b08402c5c70/src/lib/core/utils/date-conversion.ts#L11, and it is generally used at Viz for a safety belt 😄 If it should be fixed at frontend then that function may be useful.

Here is a screenshot of backend response for Observation date at scatterplot response
![GEMS1-observation-date](https://user-images.githubusercontent.com/12802305/186491953-83f38fbb-6375-4aef-8c83-6eef6d686695.png)

**Comment by asizemore** [comment] 2022-08-24 18:27
Ohhhhh interesting! This is really helpful thanks @moontrip !
So the plan is to _never_ send a time zone, correct? No time zones in scatter, line, or histogram?

**Comment by moontrip** [comment] 2022-08-24 18:41
@asizemore Actually I found one interesting observation. So when you see @jernestmyers 's screenshot above, actually seriesX returns yyyy-mm-dd format, while bin-related responses such as binStart and binEnd return ISO style: I also checked them at my dev env. So, I think they should return the same format as yyyy-mm-dd? What do you think, @dmfalke ?

**Comment by moontrip** [comment] 2022-08-24 18:48
@asizemore It raised one another question. Is the seriesX format correct? It is like "2003-01-20 - 2003-01-21" as a single data, not "2003-01-20" so I don't think the seriesX data format can be handled correctly at our code?

**Comment by asizemore** [comment] 2022-08-24 19:15
> Is the seriesX format from the backend correct? It is like "2003-01-20 - 2003-01-21" as a single data, not simply "2003-01-20"

@moontrip good question. I think in this case the response is correct since even if that binning toggle is off, the request still says to bin the data. I have a feeling we're doing this for sake of aggregating the y axis but i'd have to look back at some notes to be sure.

<img width="1740" alt="Screen Shot 2022-08-24 at 3 14 21 PM" src="https://user-images.githubusercontent.com/11710234/186503845-1d4be878-8d4e-4417-8201-8497f42c4bc2.png">

**Comment by asizemore** [comment] 2022-08-24 19:22
I'm seeing the error happen [here](https://github.com/VEuPathDB/web-components/blob/9eee6d7ab10ee1df187dd1aa6a02209ead32cd5b/src/utils/extended-axis-range-truncations.ts#L55). Perhaps something is happening when we turn on the bin toggle - when the binning toggle is off we get a nice date, but with the toggle is on we get `axisRange.min = 2010-03-01T00:00:00T00:00:00Z`.

**Comment by dmfalke** [comment] 2022-08-24 20:12
@asizemore I think the issue is with the data coming into that function. See https://github.com/VEuPathDB/web-eda/blob/1f1972cbc765419ea2f59d201e6f1a887460ab19/src/lib/core/utils/default-axis-range.ts#L102-L109, where we are appending the additional time component.

**Comment by dmfalke** [comment] 2022-08-24 20:13
It may be that in one case `defaults.rangeMax` is larger, and in another `observedMax` is larger.

**Comment by asizemore** [comment] 2022-08-24 22:39
great thank you both! PR submitted :)

**Closed** 2022-08-25 19:57 UTC

**Comment by asizemore** [comment] 2022-08-25 20:40
@SheenaTomko ready for you!
Please check that the line plot works as expected with dates, and briefly that other places we're using dates still work as expected :)

**Comment by nkittur-uga** [comment] 2022-08-26 13:38
Tested a few studies and it looks good! No errors.
