### ISSUE TITLE
Extreme error message in GEMS bar plot visualization

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/plot.data#122] opened 2021-11-22 19:29 UTC
In GEMS1, with Country subset to only include African countries, chose a box plot and set up the main variable as "Dry mouth", then chose "Case or control participant" as the overlay variable and got this error message. Plot worked fine if I chose another categorical variable from the participant entity.
<img width="1184" alt="Screen Shot 2021-11-22 at 1 25 27 PM" src="https://user-images.githubusercontent.com/54597319/142923238-d74fb2ad-9ea1-4176-a052-cc63f724cb55.png">

**Comment by moontrip** [comment] 2021-12-15 15:09
Just FYI, probably the same issue that I also observed at histogram viz as follows (GEMS1):
![histogram-error1](https://user-images.githubusercontent.com/12802305/146211754-657cdf7d-5743-4af1-b1d8-489eec07f6dd.png)

**Comment by d-callan** [comment] 2021-12-17 14:19
fixed in plot.data v1.4.2

**Closed by d-callan** 2021-12-17 14:19 UTC

**Comment by aaronwlsong** [comment] 2022-01-20 20:14
Looks good now, closing ticket.
-----------------------------------
Could not replicate the first case, the var of "case or control participant" was removed from variable list. 
![image](https://user-images.githubusercontent.com/61077845/150412978-6df0ca28-e74f-4a24-b8dd-c29cd193f553.png)

Replicate the second case with and without subset of var "country", all work fine. 
![image](https://user-images.githubusercontent.com/61077845/150412809-12e14f8b-fe49-495a-bbcb-55170c35561d.png)

FYI, this type of error looks the same as another one raised in Amazonia Brazil study(ticket: https://github.com/VEuPathDB/EdaNewIssues/issues/112, type1 ), when x=" ITN bednet count", y=" Received ITN","country". So when I tested this one, I also tested in Amazonia Brazil study, the issue is also gone. So I think this extreme error should already be successfully solved across the study. 

![image](https://user-images.githubusercontent.com/61077845/150414936-f14b3c8e-51cb-40a2-8500-624501a22a1d.png)
